apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-xig0
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0046-tenant/tkrw-pr712-0075-0046-app/devfile-sample-xig0@sha256:ffc20c6b2134d70dde33a4a21a2960792d714f5d796d5d0c450db599030ff373
        name: my-nodejs
        resources: {}
status: {}
